const YouTubeParser = (captionFile) => {
  return new Promise((resolve, reject) => {
    let captions = [];
    const domParser = new DOMParser();
    const xml = domParser.parseFromString(captionFile, 'text/xml');
    const body = xml.querySelector('body');
    const timedtext = xml.querySelector('timedtext');
    if (body && timedtext && timedtext.getAttribute('format') === '3') {
      for (let i = 0; i < body.children.length; i++) {
        let currentChild = body.children[i];
        if (currentChild.tagName === 'p') {
          let text = '';
          if (currentChild.children.length) {
            /**

            Normal caption files look like this:

            <p>This is the caption text</p>

            Autogenerated caption files look like this:

            <p>
              <s>This</s>
              <s>is</s>
              <s>the</s>
              <s>caption</s>
              <s>text</s>
            </p>

            **/
            text = [...currentChild.children].map(node => node.textContent).join("");
          } else {
            text = currentChild.textContent;
          }
          const t = currentChild.getAttribute('t');
          const d = currentChild.getAttribute('d');
          if (t && d) {
            let tNum = parseInt(t);
            let dNum = parseInt(d);
            tNum = tNum / 1000;
            dNum = dNum / 1000;
            const startTime = tNum;
            const endTime = tNum + dNum;
            if (captions[captions.length - 1] &&
                captions[captions.length - 1].endTime === endTime &&
                captions[captions.length - 1].startTime <= startTime
            ) {
              captions[captions.length - 1].text = `${captions[captions.length - 1].text}\n${text}`;
            } else {
              captions.push({
                startTime,
                endTime,
                text
              });
            }
          }
        }
      }
      if (captions.length) {
        resolve(captions);
      } else {
        reject(`Couldn't parse captions from file`);
      }
    } else {
      reject(`Can't parse invalid YouTube caption file`);
    }
  });
}

module.exports = YouTubeParser;
